# Site
baseURL = '/'
languageCode = 'fr-fr'
title = 'Muzic.Live'

# Menu
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Chroniques'
    pageRef = '/reports'
    weight = 20

[taxonomies]
  artist = 'artists'
  festival = 'festivals'

[services]
  [services.disqus]
    shortname = 'mkhelif_ml'
