# Site
baseURL = '/'
languageCode = 'fr-fr'
defaultContentLanguage = 'fr'
title = 'Muzic.Live'

# Menu
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Chroniques'
    pageRef = '/reports'
    weight = 20

# Categories
[taxonomies]
  artist = 'artists'
  festival = 'festivals'
  location = 'locations'

# Services
[services]
  [services.googleAnalytics]
    id = 'G-HE90TD2KM0'
  [services.disqus]
    shortname = 'muzic-live'
  [services.rss]
    limit = 30

# RSS
[outputs]
  home = ['html', 'rss']
  section = ['html']
  taxonomy = ['html']

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

# Markup
[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.goldmark.parser.attribute]
  block = true
