# Site
baseURL = '/'
languageCode = 'fr-fr'
title = 'Muzic.Live'

# Menu
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Chroniques'
    pageRef = '/reports'
    weight = 20

[taxonomies]
  artist = 'artists'
  festival = 'festivals'
  location = 'locations'

[services]
  [services.googleAnalytics]
    id = 'GTM-NH68JMS8'
  [services.disqus]
    shortname = 'mkhelif_ml'
  [services.rss]
    limit = 42

[outputs]
  home = ['html', 'rss']
  section = ['html']
  taxonomy = ['html']
