# Site
title = 'Muzic.Live'
baseURL = '/'
languageCode = 'fr-fr'
defaultContentLanguage = 'fr'

# Categories
[taxonomies]
  album = 'albums'
  artist = 'artists'
  festival = 'festivals'
  location = 'locations'
  event = 'events'
  new = 'news'

# Services
[services]
  [services.googleAnalytics]
    id = 'G-HE90TD2KM0'
  [services.disqus]
    shortname = 'muzic-live'
  [services.rss]
    limit = 30

# RSS
[outputs]
  home = ['html', 'rss', 'ics']
  page = ['html', 'ics']
  section = ['html']
  taxonomy = ['html']

[outputFormats]
  [outputFormats.rss]
    baseName = "feed"
  [outputFormats.ics]
    baseName = "calendar"
    mediaType = 'text/calendar'

# Markup
[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.goldmark.parser.attribute]
  block = true
